apiVersion: v1
kind: ConfigMap
metadata:
  name: modifier-ingress
  namespace: dr-system
data:
  config.yaml: |
    version: v1
    resourceModifierRules:
    - conditions:
        groupResource: ingress
        resourceNameRegex: "^web-ing$"
        namespaces:
        - web
      patches:
      - operation: replace
        path: "/spec/rules/0/host"
        value: "web.standby.example.com"
