apiVersion: v1
kind: ConfigMap
metadata:
  name: modifier-frontend-image
  namespace: dr-system
data:
  config.yaml: |
    version: v1
    resourceModifierRules:
    - conditions:
        groupResource: deployment
        resourceNameRegex: "^frontend$"
        namespaces:
        - web
      patches:
      - operation: replace
        path: "/spec/template/spec/containers/0/image"
        value: "docker.io/library/nginx:1.28"
